### ISSUE TITLE
Настройка темы проекта

### ISSUE THREAD

**Issue by horba** [horba/my-trip#1]
Что такое тема и какими параметрами она определяется - https://material.io/design/color/the-color-system.html#color-usage-and-palettes

Необходимо настроить тему для vuetify - https://vuetifyjs.com/en/customization/theme/
Т.е. необходимо определить переменные темы так, чтобы они соответсвовали значениям в дизайне. Определение темы приложения находится по [ссылке](https://www.figma.com/file/1WPfvOuZS9x7pwFlQbT1ht/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%A2%D1%83%D1%80%D0%B8%D0%B7%D0%BC?node-id=1034%3A86)
 
После определения темы, протестировать можно заимпортив различные компоненты с библиотеки, которые есть в дизайне и посмотрев насколько их цветовая гамма и прочее соответсвует дизайну без внесения каких-либо правил css.

Тема приложения 
![image](https://user-images.githubusercontent.com/11043173/80805467-043f8c80-8bb0-11ea-8f8f-9c59afef1c05.png)

Компоненты приложения по [ссылке](https://www.figma.com/file/1WPfvOuZS9x7pwFlQbT1ht/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%A2%D1%83%D1%80%D0%B8%D0%B7%D0%BC?node-id=1005%3A256)
![image](https://user-images.githubusercontent.com/11043173/80805505-2802d280-8bb0-11ea-8890-b0a6e04b5a44.png)

Ориентировочное время:
изучение материала: 4ч
определение темы: 3ч
тестирование: 4ч
исправление ошибок: 1ч
ревью и внесение изменений по стилю: 2ч

**Comment by sanioooook** [comment]
кнопки которые получились у меня  → ![image](https://user-images.githubusercontent.com/33792718/80993669-25201000-8e44-11ea-83c9-0dd179e758e3.png)

 ![image](https://user-images.githubusercontent.com/33792718/80992936-edfd2f00-8e42-11ea-9d8c-275d4fcad2f3.png) кнопки которые нарисованы в дизайне ↑
секондари кнопки - текст не соответствует, праймари кнопки - состояния не контролируемы по этому четко назначить цвет не выходит

↓ переключатели(свитчеры), которые получились у меня 
![image](https://user-images.githubusercontent.com/33792718/80995453-f2c3e200-8e46-11ea-8a4b-3a9f010378f1.png)

макет ↓
![image](https://user-images.githubusercontent.com/33792718/80995625-3b7b9b00-8e47-11ea-8741-a5f89af01d56.png)
отличия(если не брать во внимания небольшую ошибку в макете с базовым состоянием переключателя): особо никаких, кроме состояния hover, и то что кнопка свитчера не белая и тоже синяя(цвета темы)

радиокнопки: мои ↓
![image](https://user-images.githubusercontent.com/33792718/80996152-06bc1380-8e48-11ea-99bf-27495cf8504b.png)
макет ↓
![image](https://user-images.githubusercontent.com/33792718/80996034-d96f6580-8e47-11ea-8546-463c34212579.png)
отличия: кружочек в середине в макете белый, а вокруг он цвета темы должен быть, но vutify распорядился иначе:) в целом тут это отличие видно. состояния, опять те же состояния, при наведении можно либо такой себе ареол сделать вокруг радиокнопки, либо его убрать, в макете не ореол а бордюр у кнопки, так что отличие

чекбоксики: мои ↓
![image](https://user-images.githubusercontent.com/33792718/80996476-88ac3c80-8e48-11ea-9115-baa66f147b09.png)
макетные ↓
![image](https://user-images.githubusercontent.com/33792718/80996556-a8436500-8e48-11ea-9f8c-23bec9f5265d.png)
отличия: с цветом все норм, но состояние hover точно такое же как и на радиокнопке

чипсы: мои ↓
![image](https://user-images.githubusercontent.com/33792718/80996712-f35d7800-8e48-11ea-9273-238855bbcbc4.png)
макетные ↓
![image](https://user-images.githubusercontent.com/33792718/80996800-15ef9100-8e49-11ea-84af-517f9250658b.png)
чувствую что состояние hover не то что надо, но так по цвету нормально все, можно настроить, претензий вроде нет:)

поле ввода:
мое↓
![image](https://user-images.githubusercontent.com/33792718/80997031-767ece00-8e49-11ea-8f92-d8a6a7490b95.png)
макетное↓
![image](https://user-images.githubusercontent.com/33792718/80997166-9ca46e00-8e49-11ea-9301-87b20dcbd1e5.png)
тут надо выбирать с бордюром или без, на мой вариант без, но если его добавить, то он при фокусе будет цвета праймари темы(ну или какой настроить) и тогда ерор и саксесфул будет соответствовать тому что на макете

Календарь:
мое ↓
![image](https://user-images.githubusercontent.com/33792718/80997430-f7d66080-8e49-11ea-994f-9a75f12355fe.png)
макет ↓
![image](https://user-images.githubusercontent.com/33792718/80997504-163c5c00-8e4a-11ea-97ca-0538b8998b39.png)
на моем варианте серым - это выбрана вторая дата. нельзя выбрать промежуток(наверное только через функции) но и так в целом не отвечает тому что на макете, вполне возможно что его можно как-то настроить, но я не нашел, по этому так

слайдеры:
мое ↓
![image](https://user-images.githubusercontent.com/33792718/81001664-c2814100-8e50-11ea-816b-dc6092f4eca6.png)
макет↓
![image](https://user-images.githubusercontent.com/33792718/81001709-d167f380-8e50-11ea-8d44-5e1a77bfd97d.png)
отличий нет

выпадающие списки:
мое↓
![image](https://user-images.githubusercontent.com/33792718/81001786-ea70a480-8e50-11ea-84b6-84a5221b0fa6.png)
макет↓
![image](https://user-images.githubusercontent.com/33792718/81001871-07a57300-8e51-11ea-9931-79efef3900c9.png)
стрелочки скорее всего можно настроить, но выбранный элемент(его цвет) не настраивается
