### ISSUE TITLE
Страничка досуга для неавторизованного юзера

### ISSUE THREAD

**Issue by ivhorodko** [horba/my-trip#24]
Реализовать возможность поиска мест для доступа посредством апи гугл карт.

**В рамках задачи необходимо**

- [x] ознакомиться с апи гугл карт [документация здесь](https://developers.google.com/maps/documentation)
- [x] подключить гугл карту к приложению
- [x] реализовать флоу:

1. неавторизованный пользователь переходит на вкладку меню "Досуг"
2. пользователь видит перед собой гугл карту со своим текущим местоположением
3. пользователь вводит название города в поиск или другим образом задает навание места поиска для мест развлечений
4. после ввода места поиска внизу отображается список мест для досуга для выбранного города или другого места в виде плиток (может понадобится пагинация), гугл карта отображает заданное место поиска.

- [x] реализовать переключатель отображения карты

**Места досуга берутся через апи гугл карт**

**Не реализовываем:**

- добавление в закладки
- популярные запросы
- фильтры типа мест досуга

**Скипаем по причине непонятки зачем это:**

- радиус показа

[исходник дизайна](https://www.figma.com/file/1WPfvOuZS9x7pwFlQbT1ht/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%A2%D1%83%D1%80%D0%B8%D0%B7%D0%BC?node-id=1431%3A4687)
<img src="https://i.ibb.co/cbhZc0q/image.jpg"/>

**Comment by horba** [comment]
Вынесли в отдельную задачу #31 флоу поиска мест досуга. В рамках данной задачи реализовали подключение к апи и отображение карты
