### ISSUE TITLE
Меню неавторизованного пользователя: цвет и размещение

### ISSUE THREAD

**Issue by horba** [horba/my-trip#34]
В дизайне два цвета меню неавторизованого пользователя. 
Нужно выяснить какой из них корректный, если нужно поменять в стилях на нужный цвет

`#2962FF`
![image](https://user-images.githubusercontent.com/11043173/82740024-c65fff00-9d3c-11ea-89ef-5087e284e335.png)

`#03A9F4`
![image](https://user-images.githubusercontent.com/11043173/82740056-1343d580-9d3d-11ea-841e-b97493539043.png)

Также проверить что верхнее меню - фиксированное

**Comment by girinadev** [comment]
Дизайнеры ответили что не менять цвет хедера.
