### ISSUE TITLE
Авторизация: frontend

### ISSUE THREAD

**Issue by horba** [horba/my-trip#4]
В рамках зачачи:

- [x] сверстать с использованием vuetify страницу логина, без флоу авторизации через социальные сети и без футера и меню [источник](https://www.figma.com/file/1WPfvOuZS9x7pwFlQbT1ht/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%A2%D1%83%D1%80%D0%B8%D0%B7%D0%BC?node-id=1318%3A1750)
![image](https://user-images.githubusercontent.com/11043173/80808321-356f8b00-8bb7-11ea-9a15-4bf2a31422d2.png)

- [x] реализовать обращение к точке апи api/login, обработку ответа и сохранение данных о пользователе и токене на фронте с устойчивостью к обновлению страницы (по F5 данные пользователя и авторизации не обнуляются)

- [x] реализовать механизм контроля доступа к вьюшкам - т.е. механизм позволяющий запретить/разрешить переход на страницу на основании авторизации (Auth Guards)

Linked task: #3 

Материалы, которые могут помочь с пониманием задачи:
https://webdevblog.ru/autentifikacii-v-vue-s-ispolzovaniem-vuex/
https://www.digitalocean.com/community/tutorials/how-to-set-up-vue-js-authentication-and-route-handling-using-vue-router

Ориентировочное время выполнения: 
изучение материалов: 4ч
верстка логинки - 4ч
обращение к апи, сохранение - 4ч
auth guards - 4ч
тестирование и кооперация с сервером - 4ч

**Comment by valerachuk** [comment]
Инфо по авторизации https://docs.google.com/document/d/14OIHUWh43H49O2jpgoWgA6fXdY3AqjL2rQz_1JCHnrI/edit?usp=sharing

**Comment by horba** [comment]
включите доступ по ссылке)

**Comment by valerachuk** [comment]
Включил
https://docs.google.com/document/d/14OIHUWh43H49O2jpgoWgA6fXdY3AqjL2rQz_1JCHnrI/edit?usp=sharing

**Comment by horba** [comment]
можно добавить это на вики потом
